### ISSUE TITLE
✨[featrue] 마이페이지 구현

### ISSUE THREAD

**Issue by sophiehan12** [Pill-Mate/Pill-Mate-Backend#13]
## 📝 개요
- 마이페이지 개발
- 유저 정보 리턴, 개인 루틴 설정, 알림 설정
-
## ✔️ To-Do
- [x] 유저 정보 리턴
- [x] 개인 루틴 설정
- [x] 알림 설정 
- [ ] schedule, medicine_schedule db 수정
- [ ]  프론트랑 테스트
